### ISSUE TITLE
Incoming / outgoing traffic poisoning

### ISSUE THREAD

**Issue by h2non** [h2non/toxy#27]
Poisons are currently executed in the incoming traffic phase. It would be great to attach poisons that will be executed only when the proxy receives the response from the target server, allowing the poisons to determine when should be executed or not based on the server response.

Actually this feature can be achieve currently via the `useResponse()` middleware, but a convenient wrapper around it, adding a DSL for `toxy`, would be better and simple for the API consumers.

The API may look like this:
```js
proxy.outgoingPoison(poison)
proxy.useOutgoingPoison(poison)
  .withRule(rule)
```

### Tasks

- [x] Add featured test
- [x] Support filter via HTTP API outgoing and incoming poisons
- [x] Rename poisons ID in HTTP API to include the poison phase
- [x] Remove rules by phase
- [x] Add proper documentation
- [x] Add poisons phases explanation with proper graph
- [x] Add API docs
- [x] Add examples

**Comment by h2non** [comment]
This feature is related to #26

**Comment by h2non** [comment]
- [ ] Add featured test
- [ ] Support filter via HTTP API outgoing and incoming poisons
- [ ] Add proper documentation
- [ ] Add poisons phases explanation with proper graph

**Comment by h2non** [comment]
Hello `0.3.0`! Now available in `npm`
